# SciPy
<table align="left">
  <td>
    <a target="_blank" href="http://nbviewer.ipython.org/github/ShowMeAI-Hub/awesome-AI-cheatsheets/blob/main/Scipy/Scipy-cheatsheet-code.ipynb"><img src="https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg" />在nbviewer上查看notebook</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/ShowMeAI-Hub/awesome-AI-cheatsheets/blob/main/Scipy/Scipy-cheatsheet-code.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" />在Google Colab运行</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets/tree/main/Scipy/Scipy-cheatsheet-code.ipynb"><img src="https://badgen.net/badge/open/github/color=cyan?icon=github" />在Github上查看源代码</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets/Scipy/Scipy速查表.pdf"><img src="https://badgen.net/badge/download/pdf/color=white?icon=github"/>下载速查表</a>
  </td>
</table>

## 说明
**notebook by [韩信子](https://github.com/HanXinzi-AI)@[ShowMeAI](https://github.com/ShowMeAI-Hub)**

更多AI速查表资料请查看[速查表大全](https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets)

SciPy是基于NumPy创建的Python科学计算核心库，提供了众多数学算法与函数。

## 与NumPy交互

### 初始化

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
b = np.array([(1+5j, 2j, 3j), (4j, 5j, 6j)])

In [4]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]])

### 索引技巧

In [5]:
np.mgrid[0:5, 0:5]   #创建稠密栅格

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [6]:
np.ogrid[0:2, 0:2]   #创建开放栅格

[array([[0],
        [1]]),
 array([[0, 1]])]

In [7]:
np.r_[3, [0]*5, -1:1:10j]   #按行纵向堆叠数组

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [8]:
np.c_[a, a]   #按列横向堆叠数组

array([[1, 1],
       [2, 2],
       [3, 3]])

### 操控形状

In [9]:
np.transpose(b)   #转置矩阵

array([[1.+5.j, 0.+4.j],
       [0.+2.j, 0.+5.j],
       [0.+3.j, 0.+6.j]])

In [10]:
b.flatten()   #拉平数组

array([1.+5.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j])

In [11]:
np.hstack((c, c))   #按列横向堆叠数组

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ],
        [1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ],
        [3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [12]:
np.vstack((a, b))   #按行纵向堆叠数组

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [1.+5.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [13]:
np.hsplit(c, 2)   #在索引2横向分割数组

[array([[[1.5, 2. , 3. ]],
 
        [[3. , 2. , 1. ]]]),
 array([[[4., 5., 6.]],
 
        [[4., 5., 6.]]])]

In [14]:
np.vsplit(c, 2)   #在索引2纵向分割数组

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]

### 多项式

In [15]:
from numpy import poly1d

In [16]:
p = poly1d([3, 4, 5])   #创建多项式对象

### 矢量函数

In [17]:
def myfunc(a):
    if a < 0:
        return a*2
    else:
        return a/2

In [18]:
np.vectorize(myfunc)   #矢量函数

### 类型控制

In [19]:
np.real(c)   #返回数组元素的实部

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [20]:
np.imag(c)   #返回数组元素的虚部

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.real_if_close(c, tol=1000)   #如果复数接近0，返回实部

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [22]:
np.cast['f'](np.pi)   #将对象转化为数据类型

array(3.1415927, dtype=float32)

### 常用函数

In [23]:
np.angle(b, deg=True)   #返回复数的辐角

array([[78.69006753, 90.        , 90.        ],
       [90.        , 90.        , 90.        ]])

In [24]:
g = np.linspace(0, np.pi, num=5)   #创建等差数组(样本数)

In [25]:
g [3:] += np.pi

In [26]:
np.unwrap(g)   #解包

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])

In [27]:
np.logspace(0, 10, 3)   #创建等差数组(对数刻度)

array([1.e+00, 1.e+05, 1.e+10])

In [28]:
np.select([c<4], [c*2])   #根据条件返回数组列表的值

array([[[3., 4., 6.],
        [0., 0., 0.]],

       [[6., 4., 2.],
        [0., 0., 0.]]])

In [29]:
from scipy import special
special.factorial(a)   #因子

array([1., 2., 6.])

In [30]:
import scipy
scipy.special.comb(10, 3, exact=True)   #计算排列组合$$C_{10}^3$$

120

In [31]:
from scipy import misc
misc.central_diff_weights(3)   #NP点中心导数的权重

array([-0.5,  0. ,  0.5])

In [32]:
misc.derivative(myfunc, 1.0)   #查找函数在某点的第n个导数

0.5

## 线性代数

使用linalg和sparse模块。注意scipy.linalg包含了numpy.linalg，并扩展了其功能。

In [33]:
 from scipy import linalg, sparse

### 创建矩阵

In [34]:
A = np.matrix(np.random.random((2, 2)))

In [35]:
B = np.asmatrix(b)

In [36]:
C = np.mat(np.random.random((10, 5)))

In [37]:
D = np.mat([[3, 4], [5, 6]])

### 基础矩阵操作

**逆矩阵**

In [38]:
A.I   #求逆矩阵

matrix([[-0.25327031,  2.58843168],
        [ 1.20275974, -0.77494263]])

In [39]:
linalg.inv(A)   #求逆矩阵

array([[-0.25327031,  2.58843168],
       [ 1.20275974, -0.77494263]])

In [40]:
A.T   #矩阵转置

matrix([[0.26566503, 0.41232885],
        [0.88736347, 0.08682586]])

In [41]:
A.H   #共轭转置

matrix([[0.26566503, 0.41232885],
        [0.88736347, 0.08682586]])

In [42]:
np.trace(A)   #计算对角线元素的和

0.35249089510058107

**范数**

In [43]:
linalg.norm(A)   #Frobeniu范数

1.017617637071628

In [44]:
linalg.norm(A, 1)   #L1范数 (最大列汇总)

0.974189337644343

In [45]:
linalg.norm(A, np.inf)   #L范数 (最大列汇总)

1.1530285036832062

**排名**

In [46]:
np.linalg.matrix_rank(C)   #矩阵排名

5

**行列式**

In [47]:
linalg.det(A)   #行列式

-0.34281896670762335

**求解线性问题**

In [48]:
linalg.solve(A, b)   #求解稠密矩阵

array([[-0.25327031 +9.08737518j,  0.        +12.43561778j,
         0.        +14.77077915j],
       [ 1.20275974 +2.91402821j,  0.         -1.46919365j,
         0.         -1.04137653j]])

In [49]:
E = np.mat(a).T   #求解稠密矩阵

In [50]:
linalg.lstsq(D, D)   #用最小二乘法求解线性代数方程

(array([[1.00000000e+00, 3.29698799e-16],
        [2.67591619e-15, 1.00000000e+00]]),
 array([], dtype=float64),
 2,
 array([9.27110906, 0.21572392]))

**广义逆**

In [51]:
linalg.pinv(C)   #计算矩阵的伪逆(最小二乘法求解器)

array([[-0.01836107,  0.48839801, -0.77354577, -0.15300783,  0.52277402,
         0.07791463,  0.27693506, -0.13188957,  0.19517763, -0.29426094],
       [ 0.34857071, -0.12215497, -0.16260077,  0.17589514,  0.09894287,
         0.04949279,  0.04332514, -0.7564116 ,  0.59867828,  0.19265664],
       [ 0.63293288, -0.11895645,  0.15830958, -0.15509941, -0.22435947,
        -0.30016429,  0.29375901,  0.63657948, -0.37477849, -0.31617618],
       [-0.88711334, -0.39384048,  0.43868047, -0.14158081,  0.00791445,
         0.71233746, -0.31595224,  0.5916117 ,  0.18805527,  0.23333057],
       [ 0.12213004,  0.44716185,  0.29899879,  0.41017813, -0.03910791,
        -0.38756352,  0.03331016, -0.31654379, -0.38983363,  0.19814132]])

In [52]:
linalg.pinv2(C)   #计算矩阵的伪逆(SVD)

array([[-0.01836107,  0.48839801, -0.77354577, -0.15300783,  0.52277402,
         0.07791463,  0.27693506, -0.13188957,  0.19517763, -0.29426094],
       [ 0.34857071, -0.12215497, -0.16260077,  0.17589514,  0.09894287,
         0.04949279,  0.04332514, -0.7564116 ,  0.59867828,  0.19265664],
       [ 0.63293288, -0.11895645,  0.15830958, -0.15509941, -0.22435947,
        -0.30016429,  0.29375901,  0.63657948, -0.37477849, -0.31617618],
       [-0.88711334, -0.39384048,  0.43868047, -0.14158081,  0.00791445,
         0.71233746, -0.31595224,  0.5916117 ,  0.18805527,  0.23333057],
       [ 0.12213004,  0.44716185,  0.29899879,  0.41017813, -0.03910791,
        -0.38756352,  0.03331016, -0.31654379, -0.38983363,  0.19814132]])

### 创建稀疏矩阵

In [53]:
F = np.eye(3, k=1)   #创建2X2单位矩阵

In [54]:
G = np.mat(np.identity(2))   #创建2X2单位矩阵

In [55]:
C[C > 0.5] = 0

In [56]:
H = sparse.csr_matrix(C)   #压缩稀疏行矩阵

In [57]:
I = sparse.csc_matrix(D)   #压缩稀疏列矩阵

In [58]:
J = sparse.dok_matrix(A)   #DOK矩阵

In [59]:
I.todense()   #将稀疏矩阵转为全矩阵

matrix([[3, 4],
        [5, 6]])

In [60]:
sparse.isspmatrix_csc(A)   #单位稀疏矩阵

False

### 稀疏矩阵操作

**逆矩阵**

In [63]:
import scipy.sparse.linalg as linalg
linalg.inv(I)   #求逆矩阵

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Column format>

**范数**

In [64]:
linalg.norm(I)   #范数

9.273618495495704

**解决线性问题**

In [68]:
linalg.spsolve(I, I)   #稀求解疏矩阵

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

### 稀疏矩阵函数

In [69]:
sparse.linalg.expm(I)   #稀疏矩阵指数

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Column format>

### 矩阵函数

**加法**

In [70]:
np.add(A, D)   #加法

matrix([[3.26566503, 4.88736347],
        [5.41232885, 6.08682586]])

**减法**

In [71]:
np.subtract(A, D)   #减法

matrix([[-2.73433497, -3.11263653],
        [-4.58767115, -5.91317414]])

**除法**

In [72]:
np.divide(A, D)   #除法

matrix([[0.08855501, 0.22184087],
        [0.08246577, 0.01447098]])

**乘法**

In [73]:
np.multiply(D, A)   #乘法

matrix([[0.79699509, 3.54945389],
        [2.06164426, 0.52095519]])

In [74]:
np.dot(A, D)   #点积

matrix([[5.23381246, 6.38684096],
        [1.67111588, 2.1702706 ]])

In [75]:
np.vdot(A, D)   #向量点积

matrix([[0.79699509]])

In [76]:
np.inner(A, D)   #内积

matrix([[4.34644898, 6.65250599],
        [1.58429002, 2.58259945]])

In [77]:
np.outer(A, D)   #外积

array([[0.79699509, 1.06266012, 1.32832515, 1.59399018],
       [2.66209042, 3.54945389, 4.43681737, 5.32418084],
       [1.23698656, 1.64931541, 2.06164426, 2.47397312],
       [0.26047759, 0.34730346, 0.43412932, 0.52095519]])

In [78]:
np.tensordot(A, D)   #张量点积

array(6.92904843)

In [79]:
np.kron(A, D)   #Kronecker积

matrix([[0.79699509, 1.06266012, 2.66209042, 3.54945389],
        [1.32832515, 1.59399018, 4.43681737, 5.32418084],
        [1.23698656, 1.64931541, 0.26047759, 0.34730346],
        [2.06164426, 2.47397312, 0.43412932, 0.52095519]])

In [90]:
help(linalg.expm_multiply)

Help on function expm_multiply in module scipy.sparse.linalg._expm_multiply:

expm_multiply(A, B, start=None, stop=None, num=None, endpoint=None)
    Compute the action of the matrix exponential of A on B.
    
    Parameters
    ----------
    A : transposable linear operator
        The operator whose exponential is of interest.
    B : ndarray
        The matrix or vector to be multiplied by the matrix exponential of A.
    start : scalar, optional
        The starting time point of the sequence.
    stop : scalar, optional
        The end time point of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced time points, so that `stop` is excluded.
        Note that the step size changes when `endpoint` is False.
    num : int, optional
        Number of time points to use.
    endpoint : bool, optional
        If True, `stop` is the last time point.  Otherwise, it is not included.
    
   

**指数函数**

In [80]:
linalg.expm(A)   #矩阵指数

array([[1.5361597 , 1.12558146],
       [0.52302098, 1.3093101 ]])

**对数函数**

In [97]:
scipy.linalg.logm(A)   #矩阵对数

array([[-0.49189531+1.34108333j,  0.43049609-2.27957812j],
       [ 0.20003749-1.05924557j, -0.57865746+1.80050933j]])

**三角函数**

In [99]:
scipy.linalg.sinm(D)   #矩阵正弦

array([[-0.07153039,  0.17875259],
       [ 0.22344073,  0.06253405]])

In [100]:
scipy.linalg.cosm(D)   #矩阵余弦

array([[ 0.30988067, -0.82893511],
       [-1.03616888, -0.31182066]])

In [101]:
scipy.linalg.tanm(A)   #矩阵切线

array([[0.3772929 , 1.06633638],
       [0.49549172, 0.16238355]])

**双曲三角函数**

In [102]:
scipy.linalg.sinhm(D)   #双曲矩阵正弦

array([[1716.2338286 , 2134.23383225],
       [2667.79229031, 3316.90920278]])

In [103]:
scipy.linalg.coshm(D)   #双曲矩阵余弦

array([[1717.05255912, 2133.70712649],
       [2667.13390811, 3317.33290398]])

In [104]:
scipy.linalg.tanhm(A)   #双曲矩阵切线

array([[0.20172133, 0.774065  ],
       [0.35968275, 0.04571633]])

**矩阵符号函数**

In [106]:
np.sign(A)   #矩阵符号函数

matrix([[1., 1.],
        [1., 1.]])

**矩阵平方根**

In [108]:
scipy.linalg.sqrtm(A)   #矩阵平方根

array([[0.50865931+0.28161567j, 0.64400035-0.4786913j ],
       [0.29924595-0.22243223j, 0.37886753+0.37809108j]])

**任意函数**

In [109]:
scipy.linalg.funm(A, lambda x: x*x)   #评估矩阵函数

array([[0.43646347, 0.31278754],
       [0.14534217, 0.37342429]])

### 矩阵分解

**特征值与特征向量**

In [111]:
la, v = scipy.linalg.eig(A)   #求解方阵的普通或广义特征值问题

In [112]:
l1, l2 = la   #解包特征值

In [113]:
v[:, 0]   #第一个特征值

array([0.8619086 , 0.50706367])

In [114]:
v[:, 1]   #第二个特征值

array([-0.78474171,  0.61982292])

In [115]:
scipy.linalg.eigvals(A)   #解包特征值

array([ 0.78770389+0.j, -0.43521299+0.j])

**奇异值分解**

In [116]:
U, s, Vh = scipy.linalg.svd(B)   #奇异值分解(SVD)

In [117]:
M, N = B.shape

In [118]:
Sig = scipy.linalg.diagsvd(s, M, N)   #在SVD中构建Sigma矩阵

**LU 分解**

In [119]:
P, L, U = scipy.linalg.lu(C)   #LU分解

### 解构稀疏矩阵

In [120]:
la, v = sparse.linalg.eigs(F, 1)   #特征值与特征向量

In [121]:
sparse.linalg.svds(H, 2)   #奇异值分解(SVD)

(array([[-0.08884689,  0.18491492],
        [-0.52298446,  0.19976149],
        [ 0.01159765,  0.01748911],
        [ 0.05954778,  0.35940384],
        [ 0.        ,  0.        ],
        [ 0.19981333,  0.65881768],
        [ 0.        ,  0.        ],
        [ 0.17972496,  0.35148866],
        [ 0.08862015,  0.45789139],
        [-0.79676413,  0.17080778]]),
 array([0.71124383, 1.10843563]),
 array([[ 0.28316372, -0.49874568, -0.07522717, -0.8050678 ,  0.13144487],
        [ 0.66546825,  0.09519761,  0.64146554,  0.16883067,  0.32879719]]))

## 调用帮助

**help函数**

In [122]:
help(scipy.linalg.diagsvd)

Help on function diagsvd in module scipy.linalg.decomp_svd:

diagsvd(s, M, N)
    Construct the sigma matrix in SVD from singular values and size M, N.
    
    Parameters
    ----------
    s : (M,) or (N,) array_like
        Singular values
    M : int
        Size of the matrix whose singular values are `s`.
    N : int
        Size of the matrix whose singular values are `s`.
    
    Returns
    -------
    S : (M, N) ndarray
        The S-matrix in the singular value decomposition
    
    See Also
    --------
    svd : Singular value decomposition of a matrix
    svdvals : Compute singular values of a matrix.
    
    Examples
    --------
    >>> from scipy.linalg import diagsvd
    >>> vals = np.array([1, 2, 3])  # The array representing the computed svd
    >>> diagsvd(vals, 3, 4)
    array([[1, 0, 0, 0],
           [0, 2, 0, 0],
           [0, 0, 3, 0]])
    >>> diagsvd(vals, 4, 3)
    array([[1, 0, 0],
           [0, 2, 0],
           [0, 0, 3],
           [0, 0, 0]])



In [123]:
np.info(np.matrix)

 matrix()

matrix(data, dtype=None, copy=True)

.. note:: It is no longer recommended to use this class, even for linear
          algebra. Instead use regular arrays. The class may be removed
          in the future.

Returns a matrix from an array-like object, or from a string of data.
A matrix is a specialized 2-D array that retains its 2-D nature
through operations.  It has certain special operators, such as ``*``
(matrix multiplication) and ``**`` (matrix power).

Parameters
----------
data : array_like or string
   If `data` is a string, it is interpreted as a matrix with commas
   or spaces separating columns, and semicolons separating rows.
dtype : data-type
   Data-type of the output matrix.
copy : bool
   If `data` is already an `ndarray`, then this flag determines
   whether the data is copied (the default), or whether a view is
   constructed.

See Also
--------
array

Examples
--------
>>> a = np.matrix('1 2; 3 4')
>>> a
matrix([[1, 2],
        [3, 4]])

>>> np.matrix([[1,